#Product
@resourceApi=http://localhost:3000/api/data
GET  {{resourceApi}}

###
# @name filterProduct
GET  {{resourceApi}}?color=orchid&price_gte=450
###
# @name filterProduct
GET  {{resourceApi}}?_page=1&_limit=20
# @name sortProduct
GET  {{resourceApi}}?_sort=price&_order=desc

###
# @name addNew
POST {{resourceApi}}
Content-Type: application/json

{
    "categoryId": "d73657a7-ce8f14-ebb51ae08f28",
    "name": "Licensed Pla Computer",
    "color": "plum",
    "price": 90,
    "description": "The beautiful range of Appan exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
  }


###
# @name UpdateProduct
PATCH  {{resourceApi}}/qFIUD1y
Content-Type: application/json

{
    "categoryId": "d73657a7-ce8f14-ebb51ae08f28",
    "name": "Licensed Pla Computer",
    "color": "plum",
    "price": 812,
    "description": "The beautiful range of Appan exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
  }
###
# @name removeProduct
DELETE {{resourceApi}}